server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /login {
        proxy_pass http://backend:5000/login;
        proxy_connect_timeout 3s;
        proxy_read_timeout 5s;
    }

    location /trabajadores {
        proxy_pass http://backend:5000/trabajadores;
        proxy_connect_timeout 3s;
        proxy_read_timeout 5s;
    }

    location /usuarios {
        proxy_pass http://backend:5000/usuarios;
        proxy_connect_timeout 3s;
        proxy_read_timeout 5s;
    }

    location /departamentos {
        proxy_pass http://backend:5000/departamentos;
        proxy_connect_timeout 3s;
        proxy_read_timeout 5s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
